# Generated by Django 2.0.3 on 2020-10-10 12:58

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_hit_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_count', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user_hit_count',
                'verbose_name_plural': 'user_hit_counts',
            },
        ),
        migrations.RemoveField(
            model_name='user_answer',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='user_class',
        ),
        migrations.AddField(
            model_name='inspire_reg',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_link_1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_link_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_link_3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_link_4',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_link_5',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_link_6',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_pdf',
            field=models.FileField(blank=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_video_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_video_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_video_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_video_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_video_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_video_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user_answer',
            name='taketime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.classes'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_level',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Hard', 'Hard'), ('Easy', 'Easy')], max_length=20),
        ),
        migrations.AddField(
            model_name='user_hit_count',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.question'),
        ),
        migrations.AddField(
            model_name='user_hit_count',
            name='user_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.user_reg'),
        ),
    ]
