# Generated by Django 2.0.3 on 2020-10-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20201010_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectchapter',
            name='Chapter_link_1',
        ),
        migrations.RemoveField(
            model_name='subjectchapter',
            name='Chapter_link_2',
        ),
        migrations.RemoveField(
            model_name='subjectchapter',
            name='Chapter_link_3',
        ),
        migrations.RemoveField(
            model_name='subjectchapter',
            name='Chapter_link_4',
        ),
        migrations.RemoveField(
            model_name='subjectchapter',
            name='Chapter_link_5',
        ),
        migrations.RemoveField(
            model_name='subjectchapter',
            name='Chapter_link_6',
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='Chapter_pdf_internet',
            field=models.FileField(blank=True, upload_to='pdf/'),
        ),
    ]
