# Generated by Django 2.0.3 on 2021-06-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectchapter',
            name='Chapter_pdf',
        ),
        migrations.RemoveField(
            model_name='subjectchapter',
            name='Chapter_pdf_internet',
        ),
    ]
