# Generated by Django 2.0.3 on 2021-08-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20210609_0900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inspire_reg',
        ),
        migrations.DeleteModel(
            name='owner',
        ),
        migrations.RemoveField(
            model_name='question',
            name='img_op_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='img_op_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='img_op_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='img_op_4',
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('Multiple_MCQ', 'Multiple_MCQ'), ('text', 'text')], max_length=20),
        ),
    ]
