# Generated by Django 2.0.3 on 2021-08-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20210816_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'board',
                'verbose_name_plural': 'board',
            },
        ),
        migrations.CreateModel(
            name='prev_year_ques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('question', models.FileField(blank=True, upload_to='prev_year_ques/')),
                ('status', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.board')),
            ],
            options={
                'verbose_name': 'prev_year_ques',
                'verbose_name_plural': 'prev_year_ques',
            },
        ),
        migrations.CreateModel(
            name='year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=5)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'year',
                'verbose_name_plural': 'year',
            },
        ),
        migrations.AddField(
            model_name='prev_year_ques',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.year'),
        ),
    ]
