# Generated by Django 2.0.3 on 2021-08-23 06:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20210823_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='written',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='question/')),
                ('ans', models.FileField(blank=True, upload_to='ebook/')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'written',
                'verbose_name_plural': 'written',
            },
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='ebook',
            field=models.FileField(blank=True, upload_to='ebook/'),
        ),
        migrations.AddField(
            model_name='written',
            name='subjectchapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.subjectchapter'),
        ),
    ]
