# Generated by Django 2.0.3 on 2021-10-02 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20210922_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_written_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.FileField(blank=True, upload_to='ans/')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User written answer',
                'verbose_name_plural': 'User written answers',
            },
        ),
        migrations.RemoveField(
            model_name='written',
            name='ans',
        ),
        migrations.AddField(
            model_name='user_written_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.written'),
        ),
        migrations.AddField(
            model_name='user_written_answer',
            name='user_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.user_reg'),
        ),
    ]
