# Generated by Django 2.0.3 on 2021-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20211002_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reg',
            old_name='name',
            new_name='f_name',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='point',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user_reg',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='l_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
