# Generated by Django 2.0.3 on 2021-10-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_auto_20211003_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_reg',
            name='user_image',
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
