# Generated by Django 2.0.3 on 2021-10-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
        migrations.AddField(
            model_name='contact',
            name='view_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
