# Generated by Django 2.0.3 on 2021-10-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_auto_20211013_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='board_on_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.board')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.year')),
            ],
            options={
                'verbose_name': 'board_on_year',
                'verbose_name_plural': 'board_on_year',
            },
        ),
        migrations.RemoveField(
            model_name='prev_year_ques',
            name='board',
        ),
        migrations.RemoveField(
            model_name='prev_year_ques',
            name='year',
        ),
        migrations.AddField(
            model_name='prev_year_ques',
            name='year_and_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.board_on_year'),
        ),
    ]
