# Generated by Django 2.0.3 on 2021-10-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_auto_20211021_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='logo/')),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('speech', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'index speech',
                'verbose_name_plural': 'index speech',
            },
        ),
    ]
