# Generated by Django 2.0.3 on 2021-10-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_index_speech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_speech',
            name='phone',
        ),
    ]
