# Generated by Django 2.0.3 on 2021-10-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_remove_index_speech_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_hit_count',
            name='question',
        ),
    ]
