# Generated by Django 2.0.3 on 2021-10-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_remove_user_hit_count_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_on_year',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.classes'),
        ),
        migrations.AlterField(
            model_name='board_on_year',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.board'),
        ),
        migrations.AlterField(
            model_name='board_on_year',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.year'),
        ),
    ]
