# Generated by Django 2.0.3 on 2021-10-30 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0024_auto_20211030_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes_on_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.classes')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.year')),
            ],
            options={
                'verbose_name': 'classes_on_year',
                'verbose_name_plural': 'classes_on_year',
            },
        ),
        migrations.RemoveField(
            model_name='board_on_year',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='board_on_year',
            name='year',
        ),
        migrations.AddField(
            model_name='board_on_year',
            name='classes_on_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.classes_on_year'),
        ),
    ]
