# Generated by Django 2.0.3 on 2021-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0025_auto_20211030_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes_on_year',
            name='name',
        ),
        migrations.AlterField(
            model_name='board_on_year',
            name='board',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='classes_on_year',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='board',
        ),
        migrations.DeleteModel(
            name='year',
        ),
    ]
