# Generated by Django 2.0.3 on 2021-10-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0027_auto_20211030_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
